version: '3'

services:

  # run tests
  test:
    container_name: gigmsn_publisher_test
    image: alesr/gigmsn-publisher_test
    build:
      context: .
      dockerfile: resources/test/Dockerfile

  # run server
  server:
    container_name: gigmsn_server
    image: alesr/gigmsn-server
    ports:
      - "3000:3000"
    links:
      - broker:broker
    build:
      context: .
      dockerfile: resources/server/prod/Dockerfile

  # run jsclient to send mock data to server
  jsclient:
    container_name: gigmsn_jsclient
    image: alesr/gigmsn-jsclient
    links:
      - server:server
    build:
      context: .
      dockerfile: resources/jsclient/Dockerfile

  # RabbitMQ
  broker:
    container_name: gigmsn_broker
    hostname: gigmsn_broker
    ports:
      - "8080:15672"
    image: rabbitmq:3.6-management-alpine
